project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true

engine: knitr
execute: 
  freeze: auto
csl: apa.csl
website:
  title: "W. Joel Schneider"
  description: "{{< meta description-meta >}}"
  favicon: "/images/favicon.png"
  site-url: "https://wjschne.github.io"
  repo-url: "https://github.com/wjschne/schneiderwebquarto"
  open-graph: true
  navbar:
    pinned: true
    search: true
    left:
      - text: "R Blog"
        href: "blog.qmd"
      - text: "Assessment Blog"
        href: "assessingpsyche.qmd"
      - text: "Vita"
        href: "vita.qmd"
      - text: "Projects"
        href: "projects.qmd"
      - text: "Presentations"
        href: "presentations.qmd"
      - text: "Software"
        href: "software.qmd"
      - text: "Tutorials"
        href: "tutorials.qmd"
    right:
      - icon: envelope
        aria-label: Email
        href: "mailto:schneider@temple.edu"
        target: "_blank"
        rel: "noreferrer noopener"
        text: Email
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/wjschne
        target: "_blank"
        rel: "noreferrer noopener"
      - icon: rss
        href: blog.xml
format:
  html:
    theme: [minty, "style/schneider.scss", "style/apablog.scss"]
    toc: true
    toc-location: left
    html-math-method: katex
    code-copy: true
    resources: 
      - shinylive-sw.js

# Metadata stuff
pagetitle: "W. Joel Schneider"
description-meta: "W. Joel Schneider is a professor at Temple University."
author-meta: "W. Joel Schneider"
