project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true
    
execute: 
  freeze: true
csl: apa.csl
website:
  title: "W. Joel Schneider"
  description: "{{< meta description-meta >}}"
  favicon: "/images/favicon.png"
  site-url: "https://wjschne.github.io"
  repo-url: "https://github.com/wjschne/schneiderwebquarto"
  open-graph: true
  navbar:
    pinned: true
    search: true
    left:
      - text: "Blog"
        href: "blog.qmd"
      - text: "Vita"
        href: "vita.qmd"
      - text: "Projects"
        href: "projects.qmd"
      - text: "Presentations"
        href: "presentations.qmd"
      - text: "Software"
        href: "software.qmd"
    right:
      - icon: envelope
        aria-label: Email
        href: "mailto:schneider@temple.edu"
        target: "_blank"
        rel: "noreferrer noopener"
        text: Email
      - icon: github
        aria-label: GitHub
        text: GitHub
        href: https://github.com/wjschne
        target: "_blank"
        rel: "noreferrer noopener"
      - icon: mastodon
        aria-label: Mastodon
        href: https://fosstodon.org/@wjoelschneider
        target: "_blank"
        rel: "noreferrer noopener"
      - aria-label: ResearchGate
        href: "https://www.researchgate.net/profile/W-Schneider-3"
        text: "{{< ai researchgate >}}"
        target: "_blank"
      - aria-label: Google Scholar
        href: "https://scholar.google.com/citations?hl=en&pli=1&user=aojOxP4AAAAJ"
        text: "{{< ai google-scholar >}}"
        target: "_blank"
        rel: "noreferrer noopener"
      - text: "{{< ai orcid >}}"
        aria-label: ORCID
        href: "https://orcid.org/0000-0002-8393-5316"
        target: "_blank"
        rel: "noreferrer noopener"
      - text: "{{< ai osf >}}"
        aria-label: Open Science Framework
        href: "https://osf.io/whabf/"
        rel: "noreferrer noopener"
      - text: "{{< ai zotero >}}"
        aria-label: Zotero
        href: "https://www.zotero.org/wjschne"
        target: "_blank"
        rel: "noreferrer noopener"
      - text: "{{< ai stackoverflow >}}"
        aria-label: stackoverflow
        href: "https://stackoverflow.com/users/4513316/joel-schneider"
        target: "_blank"
        rel: "noreferrer noopener"
      - icon: youtube
        aria-label: YouTube
        href: "https://www.youtube.com/channel/UCFTUraTjxq743KfH-5gWrWg"
        target: "_blank"
        rel: "noreferrer noopener"
      - text: "{{< ai cv >}}"
        aria-label: Curriculum Vitae
        href: /files/schneider-vita.pdf
        target: "_blank"
        rel: "noreferrer noopener"
      - icon: rss
        href: blog.xml
format:
  html:
    theme: 
      - minty
      - schneider.scss
    css: styles.css
    toc: true
    toc-location: left
    html-math-method: katex

# Metadata stuff
pagetitle: "W. Joel Schneider"
description-meta: "W. Joel Schneider is a professor at Temple University."
author-meta: "W. Joel Schneider"
