---
title: Overture Redux
date: '2023-09-12'
---

The original title of this blog ([Assessing Psyche, Engaging Gauss, Seeking Sophia](https://assessingpsyche.wordpress.com/)) was more of an aspiration than a description. To keep things simple, going forward the blog's title will be just *AssessingPsyche*. 

The purpose of this blog remains the same from the [original post in 2010](https://assessingpsyche.wordpress.com/2010/10/07/overture/):

> When we are at our best, clinicians skilled in psychological assessment see beyond the obvious and communicate something useful and true to a person who needs our help. Uncovering something true often requires a bit of science, sometimes a little math, and always a lot of empathy. Communicating what is true so that it is useful requires still more empathy and a bit of art. We facilitate in our clients a deeper understanding of what is happening to them and present to them a different vision of what they can be.
>
> In this blog, I hope to communicate something useful and true to other professionals about psychological assessment. I hope that in communicating what I know, I will come to know more than I do now.